services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: vhir-opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${VHIR_OS_PASSWORD}
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    mem_limit: 4g
    restart: unless-stopped

volumes:
  opensearch-data:
