#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOCKER_DIR="$SCRIPT_DIR/../docker"
VHIR_DIR="$HOME/.vhir"
CONFIG_FILE="$VHIR_DIR/opensearch.yaml"
OS_URL="https://localhost:9200"

# --- 1. Check Docker ---
if ! command -v docker &>/dev/null; then
    echo "Error: Docker is not installed."
    echo "Install Docker: https://docs.docker.com/engine/install/"
    exit 1
fi

if ! docker compose version &>/dev/null; then
    echo "Error: Docker Compose (v2) is not available."
    exit 1
fi

echo "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')"

# --- 2. Generate password ---
mkdir -p "$VHIR_DIR"
if [ -f "$CONFIG_FILE" ]; then
    echo "OpenSearch config exists: $CONFIG_FILE"
    OS_PASSWORD=$(python3 -c "import yaml; print(yaml.safe_load(open('$CONFIG_FILE'))['password'])")
else
    # Generate password that passes zxcvbn score >= 3
    OS_PASSWORD="Vhir_$(openssl rand -hex 12)"
    cat > "$CONFIG_FILE" <<EOF
# Generated by setup-opensearch.sh — do not edit manually
host: https://localhost:9200
user: admin
password: $OS_PASSWORD
verify_certs: false
EOF
    chmod 600 "$CONFIG_FILE"
    echo "Generated OpenSearch config: $CONFIG_FILE"
fi

# --- 3. Start OpenSearch ---
export VHIR_OS_PASSWORD="$OS_PASSWORD"
echo "Starting OpenSearch..."
docker compose -f "$DOCKER_DIR/docker-compose.yml" up -d

# --- 4. Wait for OpenSearch to be ready ---
echo -n "Waiting for OpenSearch"
for i in $(seq 1 60); do
    if curl -sk -u "admin:$OS_PASSWORD" "$OS_URL/_cluster/health" &>/dev/null; then
        echo " ready!"
        break
    fi
    echo -n "."
    sleep 2
done

# Verify it's actually up
HEALTH=$(curl -sk -u "admin:$OS_PASSWORD" "$OS_URL/_cluster/health" 2>/dev/null || true)
if [ -z "$HEALTH" ]; then
    echo ""
    echo "Error: OpenSearch did not start within 120 seconds."
    echo "Check: docker logs vhir-opensearch"
    exit 1
fi

STATUS=$(echo "$HEALTH" | python3 -c "import sys,json; print(json.load(sys.stdin)['status'])" 2>/dev/null || echo "unknown")
echo "Cluster status: $STATUS"

# --- 5. Register index template ---
TEMPLATE_FILE="$SCRIPT_DIR/../src/opensearch_mcp/mappings/evtx_ecs_template.json"
if [ -f "$TEMPLATE_FILE" ]; then
    echo "Registering ECS index template..."
    # Delete legacy template name if it exists (renamed from vhir-evtx to vhir-evtx-ecs)
    curl -sk -u "admin:$OS_PASSWORD" -X DELETE "$OS_URL/_index_template/vhir-evtx" >/dev/null 2>&1 || true
    curl -sk -u "admin:$OS_PASSWORD" \
        -X PUT "$OS_URL/_index_template/vhir-evtx-ecs" \
        -H "Content-Type: application/json" \
        -d @"$TEMPLATE_FILE" | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Template:', 'OK' if r.get('acknowledged') else r)"
else
    echo "Warning: Template file not found: $TEMPLATE_FILE"
fi

# Register CSV index template (Phase 2)
CSV_TEMPLATE="$SCRIPT_DIR/../src/opensearch_mcp/mappings/csv_template.json"
if [ -f "$CSV_TEMPLATE" ]; then
    echo "Registering CSV index template..."
    curl -sk -u "admin:$OS_PASSWORD" \
        -X PUT "$OS_URL/_index_template/vhir-csv" \
        -H "Content-Type: application/json" \
        -d @"$CSV_TEMPLATE" | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Template:', 'OK' if r.get('acknowledged') else r)"
fi

# Register Plaso index templates (Phase 3)
PREFETCH_TEMPLATE="$SCRIPT_DIR/../src/opensearch_mcp/mappings/prefetch_template.json"
if [ -f "$PREFETCH_TEMPLATE" ]; then
    echo "Registering Prefetch index template..."
    curl -sk -u "admin:$OS_PASSWORD" \
        -X PUT "$OS_URL/_index_template/vhir-prefetch" \
        -H "Content-Type: application/json" \
        -d @"$PREFETCH_TEMPLATE" | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Template:', 'OK' if r.get('acknowledged') else r)"
fi

SRUM_TEMPLATE="$SCRIPT_DIR/../src/opensearch_mcp/mappings/srum_template.json"
if [ -f "$SRUM_TEMPLATE" ]; then
    echo "Registering SRUM index template..."
    curl -sk -u "admin:$OS_PASSWORD" \
        -X PUT "$OS_URL/_index_template/vhir-srum" \
        -H "Content-Type: application/json" \
        -d @"$SRUM_TEMPLATE" | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Template:', 'OK' if r.get('acknowledged') else r)"
fi

TRANSCRIPT_TEMPLATE="$SCRIPT_DIR/../src/opensearch_mcp/mappings/transcripts_template.json"
if [ -f "$TRANSCRIPT_TEMPLATE" ]; then
    echo "Registering Transcripts index template..."
    curl -sk -u "admin:$OS_PASSWORD" \
        -X PUT "$OS_URL/_index_template/vhir-transcripts" \
        -H "Content-Type: application/json" \
        -d @"$TRANSCRIPT_TEMPLATE" | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Template:', 'OK' if r.get('acknowledged') else r)"
fi

# Register text log parser templates (W3C, Defender, Tasks, WER, SSH)
for TPL_NAME in w3c defender tasks wer ssh vol3 json delimited accesslog; do
    TPL_FILE="$SCRIPT_DIR/../src/opensearch_mcp/mappings/${TPL_NAME}_template.json"
    if [ -f "$TPL_FILE" ]; then
        echo "Registering ${TPL_NAME} index template..."
        curl -sk -u "admin:$OS_PASSWORD" \
            -X PUT "$OS_URL/_index_template/vhir-${TPL_NAME}" \
            -H "Content-Type: application/json" \
            -d @"$TPL_FILE" | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Template:', 'OK' if r.get('acknowledged') else r)"
    fi
done

# --- 6. Smoke test ---
echo "Running smoke test..."
# Index a test doc
curl -sk -u "admin:$OS_PASSWORD" \
    -X POST "$OS_URL/case-test-evtx-smoketest/_doc/test-1?refresh=true" \
    -H "Content-Type: application/json" \
    -d '{"event.code":4624,"@timestamp":"2024-01-01T00:00:00Z","host.name":"test"}' \
    >/dev/null 2>&1

# Search for it
FOUND=$(curl -sk -u "admin:$OS_PASSWORD" \
    "$OS_URL/case-test-evtx-smoketest/_search?q=event.code:4624&size=1" 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['hits']['total']['value'])" 2>/dev/null || echo "0")

if [ "$FOUND" = "1" ]; then
    echo "  Smoke test: PASS"
else
    echo "  Smoke test: FAIL (expected 1 hit, got $FOUND)"
fi

# Clean up test index
curl -sk -u "admin:$OS_PASSWORD" -X DELETE "$OS_URL/case-test-evtx-smoketest" >/dev/null 2>&1

# --- 7. GeoIP enrichment (Phase 4) ---
echo "Configuring GeoIP enrichment..."

# Create GeoIP data source (requires internet for initial download)
GEO_RESULT=$(curl -sk -u "admin:$OS_PASSWORD" \
    -X PUT "$OS_URL/_plugins/geospatial/ip2geo/datasource/maxmind-city" \
    -H "Content-Type: application/json" \
    -d '{"endpoint":"https://geoip.maps.opensearch.org/v1/geolite2-city/manifest.json","update_interval_in_days":3}' 2>/dev/null || echo '{"error":"failed"}')
if echo "$GEO_RESULT" | python3 -c "import sys,json; r=json.load(sys.stdin); sys.exit(0 if r.get('acknowledged') else 1)" 2>/dev/null; then
    echo "  GeoIP data source: OK"
else
    echo "  GeoIP data source: skipped (requires internet or already exists)"
fi

# Create GeoIP ingest pipeline with on_failure handler
echo "Creating GeoIP ingest pipeline..."
curl -sk -u "admin:$OS_PASSWORD" \
    -X PUT "$OS_URL/_ingest/pipeline/vhir-geoip" \
    -H "Content-Type: application/json" \
    -d '{
  "description": "GeoIP enrichment for source.ip",
  "processors": [{
    "ip2geo": {
      "field": "source.ip",
      "datasource": "maxmind-city",
      "target_field": "source.geo",
      "ignore_missing": true,
      "on_failure": [{
        "set": {
          "field": "source.geo.error",
          "value": "GeoIP lookup failed: {{_ingest.on_failure_message}}"
        }
      }]
    }
  }]
}' | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Pipeline:', 'OK' if r.get('acknowledged') else r)" 2>/dev/null

# Apply GeoIP pipeline to indices with IP fields (decoupled from templates)
for PATTERN in "case-*-evtx-*" "case-*-iis-*" "case-*-httperr-*" "case-*-firewall-*" "case-*-ssh-*" "case-*-accesslog-*"; do
    curl -sk -u "admin:$OS_PASSWORD" \
        -X PUT "$OS_URL/$PATTERN/_settings" \
        -H "Content-Type: application/json" \
        -d '{"index.default_pipeline":"vhir-geoip"}' >/dev/null 2>&1 || true
done
echo "  Applied GeoIP pipeline to IP-bearing indices"

# --- 8. Security Analytics detector (Phase 4) ---
echo "Configuring Security Analytics..."

# Fetch all Windows pre-packaged Sigma rule IDs, create detector
python3 -c "
import json, sys, urllib.request, ssl

url = '$OS_URL'
auth = 'admin:$OS_PASSWORD'

# Build auth header
import base64
creds = base64.b64encode(auth.encode()).decode()
headers = {
    'Authorization': f'Basic {creds}',
    'Content-Type': 'application/json',
}
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

def api(method, path, body=None):
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(url + path, data=data, headers=headers, method=method)
    with urllib.request.urlopen(req, context=ctx) as resp:
        return json.loads(resp.read())

# Step 1: Fetch all Windows Sigma rule IDs
try:
    resp = api('POST', '/_plugins/_security_analytics/rules/_search?pre_packaged=true', {
        'query': {'match_all': {}},
        'size': 5000,
    })
    hits = resp.get('hits', {}).get('hits', [])
    rule_ids = [{'id': h['_id']} for h in hits if h.get('_source', {}).get('category') == 'windows']
    print(f'  Found {len(rule_ids)} Windows Sigma rules (from {len(hits)} total)')
except Exception as e:
    print(f'  Warning: Could not fetch Sigma rules: {e}')
    sys.exit(0)

if not rule_ids:
    print('  No Windows Sigma rules found — skipping detector creation')
    sys.exit(0)

# Step 2: Check if detector already exists
try:
    existing = api('POST', '/_plugins/_security_analytics/detectors/_search', {
        'query': {'match': {'name': 'vhir-windows'}},
        'size': 1,
    })
    if existing.get('hits', {}).get('total', {}).get('value', 0) > 0:
        print('  Detector vhir-windows already exists')
        sys.exit(0)
except Exception:
    pass

# Step 3: Create detector
detector = {
    'name': 'vhir-windows',
    'detector_type': 'windows',
    'enabled': True,
    'inputs': [{
        'detector_input': {
            'description': 'Windows Event Logs (all channels)',
            'indices': ['case-*-evtx-*'],
            'pre_packaged_rules': rule_ids,
            'custom_rules': [],
        }
    }],
    'schedule': {
        'period': {'interval': 1, 'unit': 'MINUTES'}
    },
}
try:
    result = api('POST', '/_plugins/_security_analytics/detectors', detector)
    det_id = result.get('_id', 'unknown')
    print(f'  Detector created: {det_id} ({len(rule_ids)} rules)')
except Exception as e:
    print(f'  Warning: Could not create detector: {e}')
" 2>/dev/null || echo "  Security Analytics setup: skipped (may require manual configuration)"

# --- 9. Register opensearch-mcp with gateway ---
GW_CONFIG="$VHIR_DIR/gateway.yaml"
if [ -f "$GW_CONFIG" ]; then
    if grep -q "opensearch-mcp" "$GW_CONFIG"; then
        echo "opensearch-mcp already registered in gateway config."
    else
        echo "Registering opensearch-mcp with gateway..."
        # Append opensearch-mcp backend entry
        # Insert under backends: key using Python for safe YAML manipulation
        # Use venv python (matches setup-sift.sh), not system python
        VENV_PYTHON="$VHIR_DIR/venv/bin/python"
        if [ ! -f "$VENV_PYTHON" ]; then
            VENV_PYTHON="$(which python3)"
            echo "  Warning: venv not found at $VHIR_DIR/venv — using system python3"
        fi
        "$VENV_PYTHON" -c "
import yaml
from pathlib import Path
p = Path('$GW_CONFIG')
config = yaml.safe_load(p.read_text()) or {}
backends = config.setdefault('backends', {})
backends['opensearch-mcp'] = {
    'type': 'stdio',
    'command': '$VENV_PYTHON',
    'args': ['-m', 'opensearch_mcp'],
    'env': {'OPENSEARCH_CONFIG': '$VHIR_DIR/opensearch.yaml'},
}
p.write_text(yaml.dump(config, default_flow_style=False))
"
        echo "  Added opensearch-mcp to $GW_CONFIG"
    fi
else
    echo "Warning: Gateway config not found at $GW_CONFIG"
    echo "  opensearch-mcp must be registered manually."
    echo "  Add to gateway.yaml under 'backends:':"
    echo "    opensearch-mcp:"
    echo "      type: stdio"
    echo "      command: $HOME/.vhir/venv/bin/python"
    echo '      args: ["-m", "opensearch_mcp"]'
    echo '      env: {OPENSEARCH_CONFIG: ~/.vhir/opensearch.yaml}'
fi

# --- 10. Restart gateway if running ---
if systemctl --user is-active --quiet vhir-gateway 2>/dev/null; then
    echo "Restarting gateway to pick up opensearch-mcp..."
    systemctl --user restart vhir-gateway
    echo "  Gateway restarted."
elif pgrep -f "sift.gateway" >/dev/null 2>&1; then
    echo "Note: Gateway is running but not via systemd."
    echo "  Restart it manually to discover opensearch-mcp tools."
else
    echo "Note: Gateway is not running. opensearch-mcp will be"
    echo "  discovered when the gateway starts."
fi

# --- 11. Done ---
echo ""
echo "========================================="
echo "OpenSearch is running on $OS_URL"
echo "Config: $CONFIG_FILE"
echo "Security Analytics: Sigma detector with ~1,580 Windows rules"
echo "GeoIP: enrichment pipeline configured (requires internet for DB download)"
echo ""
echo "NOTE: Existing indexed data does not have GeoIP. Re-ingest to enrich."
echo ""
echo "Next steps:"
echo "  opensearch-ingest /path/to/evtx/ --hostname SERVER01 --case incident-001"
echo "========================================="
