#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOCKER_DIR="$SCRIPT_DIR/../docker"
VHIR_DIR="$HOME/.vhir"
CONFIG_FILE="$VHIR_DIR/opensearch.yaml"
OS_URL="https://localhost:9200"

# --- 1. Check Docker ---
if ! command -v docker &>/dev/null; then
    echo "Error: Docker is not installed."
    echo "Install Docker: https://docs.docker.com/engine/install/"
    exit 1
fi

if ! docker compose version &>/dev/null; then
    echo "Error: Docker Compose (v2) is not available."
    exit 1
fi

echo "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')"

# --- 2. Generate password ---
mkdir -p "$VHIR_DIR"
if [ -f "$CONFIG_FILE" ]; then
    echo "OpenSearch config exists: $CONFIG_FILE"
    OS_PASSWORD=$(python3 -c "import yaml; print(yaml.safe_load(open('$CONFIG_FILE'))['password'])")
else
    # Generate password that passes zxcvbn score >= 3
    OS_PASSWORD="Vhir_$(openssl rand -hex 12)"
    cat > "$CONFIG_FILE" <<EOF
# Generated by setup-opensearch.sh — do not edit manually
host: https://localhost:9200
user: admin
password: $OS_PASSWORD
verify_certs: false
EOF
    chmod 600 "$CONFIG_FILE"
    echo "Generated OpenSearch config: $CONFIG_FILE"
fi

# --- 3. Start OpenSearch ---
export VHIR_OS_PASSWORD="$OS_PASSWORD"
echo "Starting OpenSearch..."
docker compose -f "$DOCKER_DIR/docker-compose.yml" up -d

# --- 4. Wait for OpenSearch to be ready ---
echo -n "Waiting for OpenSearch"
for i in $(seq 1 60); do
    if curl -sk -u "admin:$OS_PASSWORD" "$OS_URL/_cluster/health" &>/dev/null; then
        echo " ready!"
        break
    fi
    echo -n "."
    sleep 2
done

# Verify it's actually up
HEALTH=$(curl -sk -u "admin:$OS_PASSWORD" "$OS_URL/_cluster/health" 2>/dev/null || true)
if [ -z "$HEALTH" ]; then
    echo ""
    echo "Error: OpenSearch did not start within 120 seconds."
    echo "Check: docker logs vhir-opensearch"
    exit 1
fi

STATUS=$(echo "$HEALTH" | python3 -c "import sys,json; print(json.load(sys.stdin)['status'])" 2>/dev/null || echo "unknown")
echo "Cluster status: $STATUS"

# --- 5. Register index template ---
TEMPLATE_FILE="$SCRIPT_DIR/../src/opensearch_mcp/mappings/evtx_ecs_template.json"
if [ -f "$TEMPLATE_FILE" ]; then
    echo "Registering ECS index template..."
    curl -sk -u "admin:$OS_PASSWORD" \
        -X PUT "$OS_URL/_index_template/vhir-evtx-ecs" \
        -H "Content-Type: application/json" \
        -d @"$TEMPLATE_FILE" | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Template:', 'OK' if r.get('acknowledged') else r)"
else
    echo "Warning: Template file not found: $TEMPLATE_FILE"
fi

# Register CSV index template (Phase 2)
CSV_TEMPLATE="$SCRIPT_DIR/../src/opensearch_mcp/mappings/csv_template.json"
if [ -f "$CSV_TEMPLATE" ]; then
    echo "Registering CSV index template..."
    curl -sk -u "admin:$OS_PASSWORD" \
        -X PUT "$OS_URL/_index_template/vhir-csv" \
        -H "Content-Type: application/json" \
        -d @"$CSV_TEMPLATE" | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Template:', 'OK' if r.get('acknowledged') else r)"
fi

# Register Plaso index templates (Phase 3)
PREFETCH_TEMPLATE="$SCRIPT_DIR/../src/opensearch_mcp/mappings/prefetch_template.json"
if [ -f "$PREFETCH_TEMPLATE" ]; then
    echo "Registering Prefetch index template..."
    curl -sk -u "admin:$OS_PASSWORD" \
        -X PUT "$OS_URL/_index_template/vhir-prefetch" \
        -H "Content-Type: application/json" \
        -d @"$PREFETCH_TEMPLATE" | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Template:', 'OK' if r.get('acknowledged') else r)"
fi

SRUM_TEMPLATE="$SCRIPT_DIR/../src/opensearch_mcp/mappings/srum_template.json"
if [ -f "$SRUM_TEMPLATE" ]; then
    echo "Registering SRUM index template..."
    curl -sk -u "admin:$OS_PASSWORD" \
        -X PUT "$OS_URL/_index_template/vhir-srum" \
        -H "Content-Type: application/json" \
        -d @"$SRUM_TEMPLATE" | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Template:', 'OK' if r.get('acknowledged') else r)"
fi

# --- 6. Smoke test ---
echo "Running smoke test..."
# Index a test doc
curl -sk -u "admin:$OS_PASSWORD" \
    -X POST "$OS_URL/case-test-evtx-smoketest/_doc/test-1" \
    -H "Content-Type: application/json" \
    -d '{"event.code":4624,"@timestamp":"2024-01-01T00:00:00Z","host.name":"test"}' \
    >/dev/null 2>&1

# Wait for index refresh
sleep 1

# Search for it
FOUND=$(curl -sk -u "admin:$OS_PASSWORD" \
    "$OS_URL/case-test-evtx-smoketest/_search?q=event.code:4624&size=1" 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['hits']['total']['value'])" 2>/dev/null || echo "0")

if [ "$FOUND" = "1" ]; then
    echo "  Smoke test: PASS"
else
    echo "  Smoke test: FAIL (expected 1 hit, got $FOUND)"
fi

# Clean up test index
curl -sk -u "admin:$OS_PASSWORD" -X DELETE "$OS_URL/case-test-evtx-smoketest" >/dev/null 2>&1

# --- 7. Register opensearch-mcp with gateway ---
GW_CONFIG="$VHIR_DIR/gateway.yaml"
if [ -f "$GW_CONFIG" ]; then
    if grep -q "opensearch-mcp" "$GW_CONFIG"; then
        echo "opensearch-mcp already registered in gateway config."
    else
        echo "Registering opensearch-mcp with gateway..."
        # Append opensearch-mcp backend entry
        # Insert under backends: key using Python for safe YAML manipulation
        python3 -c "
import yaml
from pathlib import Path
p = Path('$GW_CONFIG')
config = yaml.safe_load(p.read_text()) or {}
backends = config.setdefault('backends', {})
backends['opensearch-mcp'] = {
    'type': 'stdio',
    'command': '$(which python3)',
    'args': ['-m', 'opensearch_mcp'],
}
p.write_text(yaml.dump(config, default_flow_style=False))
"
        echo "  Added opensearch-mcp to $GW_CONFIG"
    fi
else
    echo "Warning: Gateway config not found at $GW_CONFIG"
    echo "  opensearch-mcp must be registered manually."
    echo "  Add to gateway.yaml under 'backends:':"
    echo "    opensearch-mcp:"
    echo "      type: stdio"
    echo "      command: $(which python3)"
    echo '      args: ["-m", "opensearch_mcp"]'
fi

# --- 8. Restart gateway if running ---
if systemctl --user is-active --quiet vhir-gateway 2>/dev/null; then
    echo "Restarting gateway to pick up opensearch-mcp..."
    systemctl --user restart vhir-gateway
    echo "  Gateway restarted."
elif pgrep -f "sift.gateway" >/dev/null 2>&1; then
    echo "Note: Gateway is running but not via systemd."
    echo "  Restart it manually to discover opensearch-mcp tools."
else
    echo "Note: Gateway is not running. opensearch-mcp will be"
    echo "  discovered when the gateway starts."
fi

# --- 9. Done ---
echo ""
echo "========================================="
echo "OpenSearch is running on $OS_URL"
echo "Config: $CONFIG_FILE"
echo ""
echo "Next steps:"
echo "  opensearch-ingest /path/to/evtx/ --hostname WKSTN05 --case incident-001"
echo "========================================="
